/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../schema.json
export type CtaSection = {
  _type: "ctaSection";
  heading?: string;
  description?: string;
  cta?: SimpleCallToAction;
};

export type LatestContentSection = {
  _type: "latestContentSection";
  heading?: string;
  description?: string;
  source?: "posts" | "videos" | "both";
};

export type VideoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "video";
};

export type VideoSection = {
  _type: "videoSection";
  heading?: string;
  description?: string;
  videos?: Array<
    {
      _key: string;
    } & VideoReference
  >;
};

export type CertificateReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "certificate";
};

export type CertificateSection = {
  _type: "certificateSection";
  heading?: string;
  description?: string;
  certificates?: Array<
    {
      _key: string;
    } & CertificateReference
  >;
};

export type StatsSection = {
  _type: "statsSection";
  heading?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: "simpleStatItem";
    _key: string;
  }>;
};

export type ImageTextSection = {
  _type: "imageTextSection";
  heading?: string;
  body?: PortableText;
  image?: ImageWithAlt;
  cta?: SimpleCallToAction;
};

export type PrivateLabelSection = {
  _type: "privateLabelSection";
  heading?: string;
  description?: string;
  advantages?: Array<
    {
      _key: string;
    } & SimpleFeatureItem
  >;
  processSteps?: Array<
    {
      _key: string;
    } & SimpleFeatureItem
  >;
  cta?: SimpleCallToAction;
};

export type ApplicationAreaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "applicationArea";
};

export type ApplicationGridSection = {
  _type: "applicationGridSection";
  heading?: string;
  description?: string;
  applicationAreas?: Array<
    {
      _key: string;
    } & ApplicationAreaReference
  >;
};

export type FeatureGridSection = {
  _type: "featureGridSection";
  heading?: string;
  description?: string;
  features?: Array<
    {
      _key: string;
    } & SimpleFeatureItem
  >;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type ProductShowcaseSection = {
  _type: "productShowcaseSection";
  heading?: string;
  description?: string;
  products?: Array<
    {
      _key: string;
    } & ProductReference
  >;
};

export type HeroSection = {
  _type: "heroSection";
  eyebrow?: string;
  heading?: string;
  description?: string;
  primaryCta?: SimpleCallToAction;
  secondaryCta?: SimpleCallToAction;
  media?: ImageWithAlt;
  trustItems?: Array<{
    label?: string;
    _type: "trustItem";
    _key: string;
  }>;
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & HeroSection)
  | ({
      _key: string;
    } & ProductShowcaseSection)
  | ({
      _key: string;
    } & FeatureGridSection)
  | ({
      _key: string;
    } & ApplicationGridSection)
  | ({
      _key: string;
    } & PrivateLabelSection)
  | ({
      _key: string;
    } & ImageTextSection)
  | ({
      _key: string;
    } & StatsSection)
  | ({
      _key: string;
    } & CertificateSection)
  | ({
      _key: string;
    } & VideoSection)
  | ({
      _key: string;
    } & LatestContentSection)
  | ({
      _key: string;
    } & CtaSection)
>;

export type PackagingVariant = {
  _type: "packagingVariant";
  label?: InternationalizedArrayString;
  sku?: string;
  volume?: string;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type DownloadableDocumentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "downloadableDocument";
};

export type DocumentReference = {
  _type: "documentReference";
  document?: DownloadableDocumentReference;
  label?: InternationalizedArrayString;
};

export type SpecificationGroup = {
  _type: "specificationGroup";
  title?: InternationalizedArrayString;
  items?: Array<
    {
      _key: string;
    } & SpecificationItem
  >;
};

export type SpecificationItem = {
  _type: "specificationItem";
  label?: InternationalizedArrayString;
  value?: string;
  unit?: string;
  note?: InternationalizedArrayString;
};

export type SocialLink = {
  _type: "socialLink";
  platform?: "linkedin" | "instagram" | "youtube" | "facebook" | "x";
  url?: string;
};

export type ContactChannel = {
  _type: "contactChannel";
  department?: InternationalizedArrayString;
  phone?: string;
  email?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type FeatureItem = {
  _type: "featureItem";
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type StatItem = {
  _type: "statItem";
  value?: string;
  label?: InternationalizedArrayString;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type SimpleFeatureItem = {
  _type: "simpleFeatureItem";
  title?: string;
  description?: string;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SimpleCallToAction = {
  _type: "simpleCallToAction";
  label?: string;
  linkType?: "internal" | "external";
  internalPath?: string;
  externalUrl?: string;
  variant?: "primary" | "secondary" | "ghost";
};

export type CallToAction = {
  _type: "callToAction";
  label?: InternationalizedArrayString;
  link?: InternalOrExternalLink;
  variant?: "primary" | "secondary" | "ghost";
};

export type ProductCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productCategory";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type InternalOrExternalLink = {
  _type: "internalOrExternalLink";
  label?: InternationalizedArrayString;
  linkType?: "internal" | "external" | "reference";
  internalPath?: string;
  externalUrl?: string;
  reference?:
    | ProductReference
    | ProductCategoryReference
    | ApplicationAreaReference
    | PageReference
    | PostReference;
  openInNewTab?: boolean;
};

export type LocalizedImageWithAlt = {
  _type: "localizedImageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: InternationalizedArrayString;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Certificate = {
  _id: string;
  _type: "certificate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: InternationalizedArrayString;
  issuer?: string;
  certificateNumber?: string;
  issuedAt?: string;
  expiresAt?: string;
  logo?: ImageWithAlt;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  sortOrder?: number;
};

export type LocaleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "locale";
};

export type DownloadableDocument = {
  _id: string;
  _type: "downloadableDocument";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  documentType?: "sds" | "tds" | "catalog" | "certificate" | "userGuide";
  language?: LocaleReference;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  version?: string;
  publishedAt?: string;
  validUntil?: string;
  relatedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  legacySourceUrl?: string;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  provider?: "youtube" | "vimeo" | "mux";
  externalUrl?: string;
  playbackId?: string;
  coverImage?: ImageWithAlt;
  relatedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  publishedAt?: string;
};

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type ApplicationArea = {
  _id: string;
  _type: "applicationArea";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  summary?: InternationalizedArrayText;
  body?: InternationalizedArrayPortableText;
  coverImage?: ImageWithAlt;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  benefits?: Array<
    {
      _key: string;
    } & FeatureItem
  >;
  products?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  cta?: CallToAction;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type InternationalizedArrayPortableText = Array<
  {
    _key: string;
  } & InternationalizedArrayPortableTextValue
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  sku?: string;
  status?: "draft" | "published" | "archived";
  sortOrder?: number;
  shortDescription?: InternationalizedArrayText;
  body?: InternationalizedArrayPortableText;
  primaryCategory?: ProductCategoryReference;
  categories?: Array<
    {
      _key: string;
    } & ProductCategoryReference
  >;
  applicationAreas?: Array<
    {
      _key: string;
    } & ApplicationAreaReference
  >;
  cardImage?: LocalizedImageWithAlt;
  packshot?: LocalizedImageWithAlt;
  gallery?: Array<
    {
      _key: string;
    } & LocalizedImageWithAlt
  >;
  badge?: InternationalizedArrayString;
  featured?: boolean;
  benefits?: Array<
    {
      _key: string;
    } & FeatureItem
  >;
  features?: Array<
    {
      _key: string;
    } & FeatureItem
  >;
  usageAreas?: InternationalizedArrayPortableText;
  applicationInstructions?: InternationalizedArrayPortableText;
  warnings?: InternationalizedArrayPortableText;
  packagingVariants?: Array<
    {
      _key: string;
    } & PackagingVariant
  >;
  specificationGroups?: Array<
    {
      _key: string;
    } & SpecificationGroup
  >;
  relatedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  externalVideoUrl?: string;
  documents?: Array<
    {
      _key: string;
    } & DocumentReference
  >;
  privateLabelEligible?: boolean;
  productCta?: CallToAction;
  seo?: Seo;
  legacyId?: string;
  legacyUrls?: Array<string>;
  previousSlugs?: Array<string>;
};

export type ProductCategory = {
  _id: string;
  _type: "productCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  summary?: InternationalizedArrayText;
  body?: InternationalizedArrayPortableText;
  image?: ImageWithAlt;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  themeAccent?: "default" | "red" | "neutral";
  sortOrder?: number;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyName?: string;
  shortDescription?: InternationalizedArrayText;
  logoLight?: ImageWithAlt;
  logoDark?: ImageWithAlt;
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  siteUrl?: string;
  defaultSeo?: Seo;
  headerNavigation?: Array<
    {
      _key: string;
    } & InternalOrExternalLink
  >;
  footerColumns?: Array<{
    title?: InternationalizedArrayString;
    links?: Array<
      {
        _key: string;
      } & InternalOrExternalLink
    >;
    _type: "footerColumn";
    _key: string;
  }>;
  quoteCta?: CallToAction;
  contactChannels?: Array<
    {
      _key: string;
    } & ContactChannel
  >;
  whatsappNumber?: string;
  whatsappMessage?: InternationalizedArrayText;
  address?: InternationalizedArrayText;
  mapUrl?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  catalogs?: Array<
    {
      _key: string;
    } & DownloadableDocumentReference
  >;
  workingHours?: InternationalizedArrayText;
  footerLegalText?: InternationalizedArrayText;
  uiLabels?: {
    requestQuote?: InternationalizedArrayString;
    viewProducts?: InternationalizedArrayString;
    readMore?: InternationalizedArrayString;
    download?: InternationalizedArrayString;
  };
};

export type Locale = {
  _id: string;
  _type: "locale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tag?: string;
  default?: boolean;
  direction?: "ltr" | "rtl";
  fallback?: LocaleReference;
  enabled?: boolean;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type PrivateLabelPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "privateLabelPage";
};

export type ContactPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contactPage";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | HomePageReference
    | PrivateLabelPageReference
    | ContactPageReference
    | PageReference
    | PostReference;
  language?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  translationStatus?: "draft" | "inReview" | "complete";
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: ImageWithAlt;
  body?: PortableText;
  publishedAt?: string;
  category?: string;
  author?: string;
  relatedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  seo?: Seo;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  translationStatus?: "draft" | "inReview" | "complete";
  title?: string;
  slug?: Slug;
  pageBuilder?: PageBuilder;
  seo?: Seo;
  legacyUrls?: Array<string>;
  previousSlugs?: Array<string>;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  translationStatus?: "draft" | "inReview" | "complete";
  title?: string;
  intro?: string;
  seo?: Seo;
  pageBuilder?: PageBuilder;
  formSuccessMessage?: string;
  formErrorMessage?: string;
};

export type PrivateLabelPage = {
  _id: string;
  _type: "privateLabelPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  translationStatus?: "draft" | "inReview" | "complete";
  title?: string;
  seo?: Seo;
  pageBuilder?: PageBuilder;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  translationStatus?: "draft" | "inReview" | "complete";
  title?: string;
  seo?: Seo;
  pageBuilder?: PageBuilder;
};

export type InternationalizedArrayPortableTextValue = {
  _type: "internationalizedArrayPortableTextValue";
  value?: PortableText;
  language?: string;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CtaSection
  | LatestContentSection
  | VideoReference
  | VideoSection
  | CertificateReference
  | CertificateSection
  | StatsSection
  | ImageTextSection
  | PrivateLabelSection
  | ApplicationAreaReference
  | ApplicationGridSection
  | FeatureGridSection
  | ProductReference
  | ProductShowcaseSection
  | HeroSection
  | PageBuilder
  | PackagingVariant
  | PortableText
  | DownloadableDocumentReference
  | DocumentReference
  | SpecificationGroup
  | SpecificationItem
  | SocialLink
  | ContactChannel
  | SanityImageAssetReference
  | FeatureItem
  | StatItem
  | InternationalizedArrayString
  | SimpleFeatureItem
  | SimpleCallToAction
  | CallToAction
  | ProductCategoryReference
  | PageReference
  | PostReference
  | InternalOrExternalLink
  | LocalizedImageWithAlt
  | ImageWithAlt
  | Seo
  | SanityFileAssetReference
  | Certificate
  | LocaleReference
  | DownloadableDocument
  | Video
  | InternationalizedArrayText
  | ApplicationArea
  | SanityImageCrop
  | SanityImageHotspot
  | InternationalizedArrayPortableText
  | Slug
  | Product
  | ProductCategory
  | SiteSettings
  | Locale
  | TranslationMetadata
  | InternationalizedArrayReference
  | HomePageReference
  | PrivateLabelPageReference
  | ContactPageReference
  | InternationalizedArrayReferenceValue
  | Post
  | Page
  | ContactPage
  | PrivateLabelPage
  | HomePage
  | InternationalizedArrayPortableTextValue
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/queries/content.ts
// Variable: POST_SLUGS_QUERY
// Query: *[    _type == "post" &&    translationStatus == "complete" &&    defined(slug.current) &&    defined(language)  ]{    "slug": slug.current,    language  }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
  language: string | null;
}>;

// Source: ../sanity/queries/industries.ts
// Variable: APPLICATION_AREA_SLUGS_QUERY
// Query: *[_type == "applicationArea" && defined(slug.current)]{"slug": slug.current}
export type APPLICATION_AREA_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../sanity/queries/products.ts
// Variable: PRODUCTS_QUERY
// Query: *[    _type == "product" &&    status == "published" &&    defined(slug.current) &&    ($category == "" || primaryCategory->slug.current == $category || $category in categories[]->slug.current) &&    ($industry == "" || $industry in applicationAreas[]->slug.current) &&    (      $q == "" ||      title[language == $locale || _key == $locale][0].value match $qWildcard ||      shortDescription[language == $locale || _key == $locale][0].value match $qWildcard ||      sku match $qWildcard    )  ] | order(sortOrder asc, title[language == $locale || _key == $locale][0].value asc) {      _id,  "title": title[language == $locale || _key == $locale][0].value,  "slug": slug.current,  sku,  "shortDescription": shortDescription[language == $locale || _key == $locale][0].value,  "badge": badge[language == $locale || _key == $locale][0].value,  featured,  cardImage{  asset,  hotspot,  crop,  "alt": alt[language == $locale || _key == $locale][0].value},  packshot{  asset,  hotspot,  crop,  "alt": alt[language == $locale || _key == $locale][0].value},  primaryCategory->{    _id,    "title": title[language == $locale || _key == $locale][0].value,    "slug": slug.current  }  }
export type PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  sku: string | null;
  shortDescription: string | null;
  badge: string | null;
  featured: boolean | null;
  cardImage: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  packshot: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  primaryCategory: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
}>;

// Source: ../sanity/queries/products.ts
// Variable: PRODUCT_SLUGS_QUERY
// Query: *[_type == "product" && status == "published" && defined(slug.current)]{"slug": slug.current}
export type PRODUCT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../sanity/queries/products.ts
// Variable: PRODUCT_CATEGORY_SLUGS_QUERY
// Query: *[_type == "productCategory" && defined(slug.current)]{"slug": slug.current}
export type PRODUCT_CATEGORY_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../sanity/queries/products.ts
// Variable: FILTER_INDUSTRIES_QUERY
// Query: *[_type == "applicationArea" && defined(slug.current)] | order(title[language == $locale || _key == $locale][0].value asc) {    _id,    "title": title[language == $locale || _key == $locale][0].value,    "slug": slug.current  }
export type FILTER_INDUSTRIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
}>;

// Source: ../sanity/queries/site-settings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    _id,    companyName,    siteUrl,    whatsappNumber,    "whatsappMessage": whatsappMessage[language == $locale || _key == $locale][0].value,    "shortDescription": shortDescription[language == $locale || _key == $locale][0].value,    "address": address[language == $locale || _key == $locale][0].value,    "workingHours": workingHours[language == $locale || _key == $locale][0].value,    "footerLegalText": footerLegalText[language == $locale || _key == $locale][0].value,    logoLight{      asset,      alt    },    logoDark{      asset,      alt    },    headerNavigation[]{      _key,      _type,      linkType,      internalPath,      externalUrl,      openInNewTab,      "label": label[language == $locale || _key == $locale][0].value,      reference->{        _type,        "slug": slug.current,        language      }    },    quoteCta{      variant,      "label": label[language == $locale || _key == $locale][0].value,      link{        linkType,        internalPath,        externalUrl,        openInNewTab,        "label": label[language == $locale || _key == $locale][0].value,        reference->{          _type,          "slug": slug.current,          language        }      }    },    contactChannels[]{      _key,      phone,      email,      "department": department[language == $locale || _key == $locale][0].value    },    socialLinks[]{      _key,      platform,      url    },    uiLabels{      "requestQuote": requestQuote[language == $locale || _key == $locale][0].value,      "viewProducts": viewProducts[language == $locale || _key == $locale][0].value,      "readMore": readMore[language == $locale || _key == $locale][0].value,      "download": download[language == $locale || _key == $locale][0].value    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  companyName: string | null;
  siteUrl: string | null;
  whatsappNumber: string | null;
  whatsappMessage: string | null;
  shortDescription: string | null;
  address: string | null;
  workingHours: string | null;
  footerLegalText: string | null;
  logoLight: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  logoDark: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  headerNavigation: Array<{
    _key: string;
    _type: "internalOrExternalLink";
    linkType: "external" | "internal" | "reference" | null;
    internalPath: string | null;
    externalUrl: string | null;
    openInNewTab: boolean | null;
    label: string | null;
    reference:
      | {
          _type: "applicationArea";
          slug: string | null;
          language: null;
        }
      | {
          _type: "page";
          slug: string | null;
          language: string | null;
        }
      | {
          _type: "post";
          slug: string | null;
          language: string | null;
        }
      | {
          _type: "product";
          slug: string | null;
          language: null;
        }
      | {
          _type: "productCategory";
          slug: string | null;
          language: null;
        }
      | null;
  }> | null;
  quoteCta: {
    variant: "ghost" | "primary" | "secondary" | null;
    label: string | null;
    link: {
      linkType: "external" | "internal" | "reference" | null;
      internalPath: string | null;
      externalUrl: string | null;
      openInNewTab: boolean | null;
      label: string | null;
      reference:
        | {
            _type: "applicationArea";
            slug: string | null;
            language: null;
          }
        | {
            _type: "page";
            slug: string | null;
            language: string | null;
          }
        | {
            _type: "post";
            slug: string | null;
            language: string | null;
          }
        | {
            _type: "product";
            slug: string | null;
            language: null;
          }
        | {
            _type: "productCategory";
            slug: string | null;
            language: null;
          }
        | null;
    } | null;
  } | null;
  contactChannels: Array<{
    _key: string;
    phone: string | null;
    email: string | null;
    department: string | null;
  }> | null;
  socialLinks: Array<{
    _key: string;
    platform: "facebook" | "instagram" | "linkedin" | "x" | "youtube" | null;
    url: string | null;
  }> | null;
  uiLabels: {
    requestQuote: string | null;
    viewProducts: string | null;
    readMore: string | null;
    download: string | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n    _type == "post" &&\n    translationStatus == "complete" &&\n    defined(slug.current) &&\n    defined(language)\n  ]{\n    "slug": slug.current,\n    language\n  }\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "applicationArea" && defined(slug.current)]{"slug": slug.current}\n': APPLICATION_AREA_SLUGS_QUERY_RESULT;
    '\n  *[\n    _type == "product" &&\n    status == "published" &&\n    defined(slug.current) &&\n    ($category == "" || primaryCategory->slug.current == $category || $category in categories[]->slug.current) &&\n    ($industry == "" || $industry in applicationAreas[]->slug.current) &&\n    (\n      $q == "" ||\n      title[language == $locale || _key == $locale][0].value match $qWildcard ||\n      shortDescription[language == $locale || _key == $locale][0].value match $qWildcard ||\n      sku match $qWildcard\n    )\n  ] | order(sortOrder asc, title[language == $locale || _key == $locale][0].value asc) {\n    \n  _id,\n  "title": title[language == $locale || _key == $locale][0].value,\n  "slug": slug.current,\n  sku,\n  "shortDescription": shortDescription[language == $locale || _key == $locale][0].value,\n  "badge": badge[language == $locale || _key == $locale][0].value,\n  featured,\n  cardImage{\n  asset,\n  hotspot,\n  crop,\n  "alt": alt[language == $locale || _key == $locale][0].value\n},\n  packshot{\n  asset,\n  hotspot,\n  crop,\n  "alt": alt[language == $locale || _key == $locale][0].value\n},\n  primaryCategory->{\n    _id,\n    "title": title[language == $locale || _key == $locale][0].value,\n    "slug": slug.current\n  }\n\n  }\n': PRODUCTS_QUERY_RESULT;
    '\n  *[_type == "product" && status == "published" && defined(slug.current)]{"slug": slug.current}\n': PRODUCT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "productCategory" && defined(slug.current)]{"slug": slug.current}\n': PRODUCT_CATEGORY_SLUGS_QUERY_RESULT;
    '\n  *[_type == "applicationArea" && defined(slug.current)] | order(title[language == $locale || _key == $locale][0].value asc) {\n    _id,\n    "title": title[language == $locale || _key == $locale][0].value,\n    "slug": slug.current\n  }\n': FILTER_INDUSTRIES_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0]{\n    _id,\n    companyName,\n    siteUrl,\n    whatsappNumber,\n    "whatsappMessage": whatsappMessage[language == $locale || _key == $locale][0].value,\n    "shortDescription": shortDescription[language == $locale || _key == $locale][0].value,\n    "address": address[language == $locale || _key == $locale][0].value,\n    "workingHours": workingHours[language == $locale || _key == $locale][0].value,\n    "footerLegalText": footerLegalText[language == $locale || _key == $locale][0].value,\n    logoLight{\n      asset,\n      alt\n    },\n    logoDark{\n      asset,\n      alt\n    },\n    headerNavigation[]{\n      _key,\n      _type,\n      linkType,\n      internalPath,\n      externalUrl,\n      openInNewTab,\n      "label": label[language == $locale || _key == $locale][0].value,\n      reference->{\n        _type,\n        "slug": slug.current,\n        language\n      }\n    },\n    quoteCta{\n      variant,\n      "label": label[language == $locale || _key == $locale][0].value,\n      link{\n        linkType,\n        internalPath,\n        externalUrl,\n        openInNewTab,\n        "label": label[language == $locale || _key == $locale][0].value,\n        reference->{\n          _type,\n          "slug": slug.current,\n          language\n        }\n      }\n    },\n    contactChannels[]{\n      _key,\n      phone,\n      email,\n      "department": department[language == $locale || _key == $locale][0].value\n    },\n    socialLinks[]{\n      _key,\n      platform,\n      url\n    },\n    uiLabels{\n      "requestQuote": requestQuote[language == $locale || _key == $locale][0].value,\n      "viewProducts": viewProducts[language == $locale || _key == $locale][0].value,\n      "readMore": readMore[language == $locale || _key == $locale][0].value,\n      "download": download[language == $locale || _key == $locale][0].value\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
